import Mathlib.Data.Matrix.Basic
import Mathlib.LinearAlgebra.Matrix.Notation
import Mathlib.LinearAlgebra.Matrix.Trace
import Mathlib.Data.Complex.Basic
import Mathlib.Algebra.BigOperators.Fin
import Mathlib.Tactic.Ring
import Mathlib.Tactic.LinearCombination
import Mathlib.Tactic.FinCases

/-! Pure algebra for the m = 1 base case: explicit 12x12 matrices of `HC 1 θ` and
`HCprime 1 θ` in the variables `c = cos(θ/2)`, `s = sin(θ/2)`, `j = I`, ordered by
`vertexOrder 1` = (0,0),(1,0),(0,1),(2,0),(1,1),(0,2), two components per vertex.
Generated by a script and symbolically verified there. -/

set_option maxHeartbeats 8000000

namespace EvgenyTheorem

open Matrix

def HC12 (c s j : ℂ) : Matrix (Fin 12) (Fin 12) ℂ := !![
  (2), (0), (-c), (j*s), (-1), (0), (0), (0), (0), (0), (0), (0);
  (0), (2), (j*s), (-c), (0), (-1), (0), (0), (0), (0), (0), (0);
  (-c), (-j*s), (4), (0), (-1), (0), (-c), (s), (-1), (0), (0), (0);
  (-j*s), (-c), (0), (4), (0), (-1), (-s), (-c), (0), (-1), (0), (0);
  (-1), (0), (-1), (0), (4), (0), (0), (0), (-c + j*s), (0), (-1), (0);
  (0), (-1), (0), (-1), (0), (4), (0), (0), (0), (-c - j*s), (0), (-1);
  (0), (0), (-c), (-s), (0), (0), (2), (0), (-1), (0), (0), (0);
  (0), (0), (s), (-c), (0), (0), (0), (2), (0), (-1), (0), (0);
  (0), (0), (-1), (0), (-c - j*s), (0), (-1), (0), (4), (0), (-1), (0);
  (0), (0), (0), (-1), (0), (-c + j*s), (0), (-1), (0), (4), (0), (-1);
  (0), (0), (0), (0), (-1), (0), (0), (0), (-1), (0), (2), (0);
  (0), (0), (0), (0), (0), (-1), (0), (0), (0), (-1), (0), (2)
]

def HCp12 (c s j : ℂ) : Matrix (Fin 12) (Fin 12) ℂ := !![
  (2), (0), (-c + j*s), (0), (-1), (0), (0), (0), (0), (0), (0), (0);
  (0), (2), (0), (-c - j*s), (0), (-1), (0), (0), (0), (0), (0), (0);
  (-c - j*s), (0), (4), (0), (-1), (0), (-c + j*s), (0), (-1), (0), (0), (0);
  (0), (-c + j*s), (0), (4), (0), (-1), (0), (-c - j*s), (0), (-1), (0), (0);
  (-1), (0), (-1), (0), (4), (0), (0), (0), (-c + j*s), (0), (-1), (0);
  (0), (-1), (0), (-1), (0), (4), (0), (0), (0), (-c - j*s), (0), (-1);
  (0), (0), (-c - j*s), (0), (0), (0), (2), (0), (-1), (0), (0), (0);
  (0), (0), (0), (-c + j*s), (0), (0), (0), (2), (0), (-1), (0), (0);
  (0), (0), (-1), (0), (-c - j*s), (0), (-1), (0), (4), (0), (-1), (0);
  (0), (0), (0), (-1), (0), (-c + j*s), (0), (-1), (0), (4), (0), (-1);
  (0), (0), (0), (0), (-1), (0), (0), (0), (-1), (0), (2), (0);
  (0), (0), (0), (0), (0), (-1), (0), (0), (0), (-1), (0), (2)
]

def HC12sq (c s j : ℂ) : Matrix (Fin 12) (Fin 12) ℂ := !![
  (c^2 - j^2*s^2 + 5), (0), (1 - 6*c), (6*j*s), (c - 6), (-j*s), (c^2 - j*s^2), (-c*j*s - c*s), (2*c - j*s), (-j*s), (1), (0);
  (0), (c^2 - j^2*s^2 + 5), (6*j*s), (1 - 6*c), (-j*s), (c - 6), (-c*j*s + c*s), (c^2 + j*s^2), (-j*s), (2*c + j*s), (0), (1);
  (1 - 6*c), (-6*j*s), (2*c^2 - j^2*s^2 + s^2 + 18), (0), (2*c + j*s - 8), (j*s), (1 - 6*c), (6*s), (2*c - j*s - 8), (-s), (2), (0);
  (-6*j*s), (1 - 6*c), (0), (2*c^2 - j^2*s^2 + s^2 + 18), (j*s), (2*c - j*s - 8), (-6*s), (1 - 6*c), (s), (2*c + j*s - 8), (0), (2);
  (c - 6), (j*s), (2*c - j*s - 8), (-j*s), (c^2 - j^2*s^2 + 19), (0), (2*c - j*s), (-s), (-8*c + 8*j*s + 2), (0), (c - j*s - 6), (0);
  (j*s), (c - 6), (-j*s), (2*c + j*s - 8), (0), (c^2 - j^2*s^2 + 19), (s), (2*c + j*s), (0), (-8*c - 8*j*s + 2), (0), (c + j*s - 6);
  (c^2 + j*s^2), (c*j*s + c*s), (1 - 6*c), (-6*s), (2*c + j*s), (s), (c^2 + s^2 + 5), (0), (c - 6), (s), (1), (0);
  (c*j*s - c*s), (c^2 - j*s^2), (6*s), (1 - 6*c), (-s), (2*c - j*s), (0), (c^2 + s^2 + 5), (-s), (c - 6), (0), (1);
  (2*c + j*s), (j*s), (2*c + j*s - 8), (s), (-8*c - 8*j*s + 2), (0), (c - 6), (-s), (c^2 - j^2*s^2 + 19), (0), (c + j*s - 6), (0);
  (j*s), (2*c - j*s), (-s), (2*c - j*s - 8), (0), (-8*c + 8*j*s + 2), (s), (c - 6), (0), (c^2 - j^2*s^2 + 19), (0), (c - j*s - 6);
  (1), (0), (2), (0), (c + j*s - 6), (0), (1), (0), (c - j*s - 6), (0), (6), (0);
  (0), (1), (0), (2), (0), (c - j*s - 6), (0), (1), (0), (c + j*s - 6), (0), (6)
]

def HCp12sq (c s j : ℂ) : Matrix (Fin 12) (Fin 12) ℂ := !![
  (c^2 - j^2*s^2 + 5), (0), (-6*c + 6*j*s + 1), (0), (c - j*s - 6), (0), (c^2 - 2*c*j*s + j^2*s^2), (0), (2*c - 2*j*s), (0), (1), (0);
  (0), (c^2 - j^2*s^2 + 5), (0), (-6*c - 6*j*s + 1), (0), (c + j*s - 6), (0), (c^2 + 2*c*j*s + j^2*s^2), (0), (2*c + 2*j*s), (0), (1);
  (-6*c - 6*j*s + 1), (0), (2*c^2 - 2*j^2*s^2 + 18), (0), (2*c + 2*j*s - 8), (0), (-6*c + 6*j*s + 1), (0), (2*c - 2*j*s - 8), (0), (2), (0);
  (0), (-6*c + 6*j*s + 1), (0), (2*c^2 - 2*j^2*s^2 + 18), (0), (2*c - 2*j*s - 8), (0), (-6*c - 6*j*s + 1), (0), (2*c + 2*j*s - 8), (0), (2);
  (c + j*s - 6), (0), (2*c - 2*j*s - 8), (0), (c^2 - j^2*s^2 + 19), (0), (2*c - 2*j*s), (0), (-8*c + 8*j*s + 2), (0), (c - j*s - 6), (0);
  (0), (c - j*s - 6), (0), (2*c + 2*j*s - 8), (0), (c^2 - j^2*s^2 + 19), (0), (2*c + 2*j*s), (0), (-8*c - 8*j*s + 2), (0), (c + j*s - 6);
  (c^2 + 2*c*j*s + j^2*s^2), (0), (-6*c - 6*j*s + 1), (0), (2*c + 2*j*s), (0), (c^2 - j^2*s^2 + 5), (0), (c + j*s - 6), (0), (1), (0);
  (0), (c^2 - 2*c*j*s + j^2*s^2), (0), (-6*c + 6*j*s + 1), (0), (2*c - 2*j*s), (0), (c^2 - j^2*s^2 + 5), (0), (c - j*s - 6), (0), (1);
  (2*c + 2*j*s), (0), (2*c + 2*j*s - 8), (0), (-8*c - 8*j*s + 2), (0), (c - j*s - 6), (0), (c^2 - j^2*s^2 + 19), (0), (c + j*s - 6), (0);
  (0), (2*c - 2*j*s), (0), (2*c - 2*j*s - 8), (0), (-8*c + 8*j*s + 2), (0), (c + j*s - 6), (0), (c^2 - j^2*s^2 + 19), (0), (c - j*s - 6);
  (1), (0), (2), (0), (c + j*s - 6), (0), (1), (0), (c - j*s - 6), (0), (6), (0);
  (0), (1), (0), (2), (0), (c - j*s - 6), (0), (1), (0), (c + j*s - 6), (0), (6)
]

theorem HC12_sq (c s j : ℂ) : HC12 c s j * HC12 c s j = HC12sq c s j := by
  ext a b
  fin_cases a <;> fin_cases b <;>
    simp [HC12, HC12sq, Matrix.mul_apply, Fin.sum_univ_succ] <;> ring

theorem HCp12_sq (c s j : ℂ) : HCp12 c s j * HCp12 c s j = HCp12sq c s j := by
  ext a b
  fin_cases a <;> fin_cases b <;>
    simp [HCp12, HCp12sq, Matrix.mul_apply, Fin.sum_univ_succ] <;> ring

/-- The base-case identity, as pure algebra (only `j^2 = -1` is needed). -/
theorem alg_base (c s j : ℂ) (hj : j ^ 2 = -1) :
    Matrix.trace (HC12 c s j * HC12 c s j * HC12 c s j * HC12 c s j) -
      Matrix.trace (HCp12 c s j * HCp12 c s j * HCp12 c s j * HCp12 c s j)
      = -32 * s ^ 2 := by
  rw [Matrix.mul_assoc (HC12 c s j * HC12 c s j), HC12_sq,
    Matrix.mul_assoc (HCp12 c s j * HCp12 c s j), HCp12_sq]
  simp [HC12sq, HCp12sq, Matrix.trace, Matrix.mul_apply, Fin.sum_univ_succ]
  linear_combination (16*c^2*s^2 - 12*j^2*s^4 + 4*s^4 + 280*s^2) * hj

end EvgenyTheorem
